# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: teracy/angular-cli:latest


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
   - npm install
   - ng build
   - npx tsc --project src-express/

test_e2e:
  stage: test
  script:
   - ng e2e

test_dev:
  stage: test
  script:
   - ng test --browsers Chrome_no_sandbox --watch false

test_prod:
  stage: test
  script:
   - npm install
   - ng version
   - ng test --prod --browsers Chrome_no_sandbox --watch false

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.review.sns-discord-formatter.fatboy.anhnhan.de
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review app"
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.sns-discord-formatter.fatboy.anhnhan.de
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://sns-discord-formatter.fatboy.anhnhan.de
  when: manual
  only:
  - master
