# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: teracy/angular-cli:latest


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - cleanup

build:
  stage: build
  script:
   - npm version
   - npm install
   - ng version
   - ng build
   - npx tsc --project src-express/

test_e2e:
  stage: test
  script:
   - ng e2e

test_dev:
  stage: test
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - coverage/
  script:
   - ng test --browsers Chrome_no_sandbox --watch false

test_prod:
  stage: test
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - coverage/
  script:
   - npm install
   - ng version
   - ng test --prod --browsers Chrome_no_sandbox --watch false

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml
