# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: teracy/angular-cli:latest


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - ng version

test_e2e:
  stage: test
  script:
   - npx ng e2e

test_dev:
  stage: test
  script:
   - npx ng test --browsers Chrome_no_sandbox --watch false

test_prod:
  stage: test
  script:
   - npx ng test --prod --browsers Chrome_no_sandbox --watch false

build_dev:
  stage: build
  dependencies:
    - test_dev
  script:
    - docker build -t registry.gitlab.anhnhan.de/converge/discord/dev/sns-discord-formatter .
    - docker push registry.gitlab.anhnhan.de/converge/discord/dev/sns-discord-formatter

build_prod:
  stage: build
  dependencies:
    - test_prod
  script:
    - docker build -t registry.gitlab.anhnhan.de/converge/discord/sns-discord-formatter .
    - docker push registry.gitlab.anhnhan.de/converge/discord/sns-discord-formatter

deploy_review:
  stage: deploy
  dependencies:
    - build_dev
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
    on_stop: stop_review
  only:
    - branches
  except:
    - master

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review app"
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

deploy_staging:
  stage: deploy
  dependencies:
    - build_dev
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.sns-discord-formatter.fatboy.anhnhan.de
  only:
  - master

deploy_prod:
  stage: deploy
  dependencies:
    - build_prod
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://sns-discord-formatter.fatboy.anhnhan.de
  when: manual
  only:
  - master
